language: android
android:
  components:
    - tools 
    - tools # see https://github.com/travis-ci/travis-ci/issues/
    - platform-tools
    - build-tools-24.0.3
    - android-24

script:
  - ./gradlew build